# protocol_name: clientCustomCharacter
# protocol_id: 0XF110
# protocol_description: 客户端绘制字符

uint16 data_cmd_id
uint16 send_id
uint16 receiver_id
GraphicData_Type grapic_data_struct
uint8[30] data
---
string result